axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('myaxf.urls', namespace='axf'))
]

myaxf/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import *

urlpatterns = [
    url(r'^home/', home, name='home'),
    url(r'^market/', market, name='market'),
    url(r'^cart/', cart, name='cart'),
    url(r'^mine/', mine, name='mine'),
    url(r'^market_with_params/(\d+)/(\d+)/(\d+)', market_with_params, name='market_params'),
    url(r'^register&', RegisterAPI.as_view(), name='register'),
    url(r'^login$', LoginAPI.as_view(), name='login'),
    url(r'^logout$', LogoutAPI.as_view(), name='logout'),
    url(r'^confirm/(.*)', confirm),
    url(r'^check_uname$', check_uname),
    url(r'^cart_api$', CartAPI.as_view()),
    url(r'^cart_status$', CartStatusAPI.as_view()),
    url(r'^cart_all_status$', CartAllStatusAPI.as_view()),
    url(r'^cart_item$', CartItemAPI.as_view()),
    url(r'^order$', OrderAPI.as_view(), name='order')
]

templates/cart/cart.html
{% extends 'base/base_main.html' %}

{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/cart/css/cart.css' %}">
{% endblock %}


{% block content %}
    <div id="cart">
        <h3>{{ title }}</h3>
        <div class="full">
            <section>
                <ul>
                    <li>收货人:{{ uname }}
                        <div>
                            <p>修改&gt;&gt;</p>
                        </div>
                    </li>
                    <li>电话:{{ phone }}</li>
                    <li>收货地址:{{ address }}</li>
                </ul>
                <div class="bill">
                    <p>闪送超市</p>
                    <a href="#">凑单专区</a>
                    <p>满一百减99,欢迎来搞</p>
                </div>
                <div class="delivery">
                    <span>收货时间:</span>
                    <span>一小时送达</span>
                    <a href="#">可预订&gt;&gt;</a>
                </div>
                <div class="delivery">
                    <span>留言备注:</span>
                    <input type="text" placeholder="如需其他服务,请备注">
                </div>
                <menu>
                    <ul>
                        {% for cart_item in cart_items %}
                            <li class="menuList" c_id="{{ cart_item.id }}">
                                <div class="confirm">
                                    <span>
                                        {% if cart_item.is_selected %}
                                            <span>√</span>
                                        {% else %}
                                            <span></span>
                                        {% endif %}
                                    </span>
                                </div>

                                <a href="">
                                    <img src="{{ cart_item.goods.productimg }}" alt="#">
                                    <p>{{ cart_item.goods.productlongname }}</p>
                                    <p>￥{{ cart_item.goods.price }}</p>
                                </a>

                                <section>
                                    <button class="subBtn">-</button>
                                    <span>{{ cart_item.num }}</span>
                                    <button class="addBtn">+</button>
                                </section>
                            </li>
                        {% endfor %}

                    </ul>
                </menu>
                <div class="payTheBill">
                    <div class="all_select">
                        <span>
                            {% if is_all_select %}
                                <span>√</span>
                            {% else %}
                                <span></span>
                            {% endif %}
                        </span>
                    </div>
                    <p>
                        <span>全选</span>
                        <span>共计:</span>
                        <span id="money_id">{{ sum_money }}</span>
                    </p>

{#                跳转到订单页#}
                    <span id="order">
{#                        <a href="{% url 'axf:order' %}">下单</a>#}
                        下单
                    </span>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/cart/js/cart.js' %}"></script>
{% endblock %}