axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('myaxf.urls', namespace='axf'))
]

myaxf/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import *

urlpatterns = [
    url(r'^home/', home, name='home'),
    url(r'^market/', market, name='market'),
    url(r'^cart/', cart, name='cart'),
    url(r'^mine/', mine, name='mine'),
    url(r'^market_with_params/(\d+)/(\d+)/(\d+)', market_with_params, name='market_params'),
    url(r'^register&', RegisterAPI.as_view(), name='register'),
    url(r'^login$', LoginAPI.as_view(), name='login'),
    url(r'^logout$', LogoutAPI.as_view(), name='logout'),
    url(r'^confirm/(.*)', confirm),
    url(r'^check_uname$', check_uname),
    url(r'^cart_api$', CartAPI.as_view()),
    url(r'^cart_status$', CartStatusAPI.as_view()),
    url(r'^cart_all_status$', CartAllStatusAPI.as_view()),
    url(r'^cart_item$', CartItemAPI.as_view()),
    url(r'^order$', OrderAPI.as_view(), name='order')
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% block css %}
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
        <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% endblock %}
</head>
<body>
    {% block header %}

    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block footer %}

    {% endblock %}
</body>
{% block js %}
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
{% endblock %}
</html>

templates/base/base_main.html
{% extends 'base/base.html' %}

{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}


{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>
                    首页
                </dd>
            </dl>
        </a>
        <a href="{% url 'axf:market' %}" class="market">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>
                    闪购
                </dd>
            </dl>
        </a>
        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>
                    购物车
                </dd>
            </dl>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>
                    我的
                </dd>
            </dl>
        </a>
    </footer>
{% endblock %}

templates/base/base_user.html
{% extends 'base/base.html' %}
{{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/user/css/user.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/md5.js' %}"></script>
{% endblock %}